[agent]
  interval = "10s"
  round_interval = true

[[outputs.graphite]]
  servers = ["graphite:2003"]
  prefix = "telegraf"

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.mem]]

[[inputs.system]]

[[inputs.net]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "overlay"]